/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	typ0crdv1 "operator-v1/pkg/apis/typ0crd/v1"
	versioned "operator-v1/pkg/client/typ0crd/clientset/versioned"
	internalinterfaces "operator-v1/pkg/client/typ0crd/informers/externalversions/internalinterfaces"
	v1 "operator-v1/pkg/client/typ0crd/listers/typ0crd/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// Typ0crdInformer provides access to a shared informer and lister for
// Typ0crds.
type Typ0crdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.Typ0crdLister
}

type typ0crdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTyp0crdInformer constructs a new informer for Typ0crd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTyp0crdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTyp0crdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTyp0crdInformer constructs a new informer for Typ0crd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTyp0crdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().Typ0crds(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().Typ0crds(namespace).Watch(options)
			},
		},
		&typ0crdv1.Typ0crd{},
		resyncPeriod,
		indexers,
	)
}

func (f *typ0crdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTyp0crdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *typ0crdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&typ0crdv1.Typ0crd{}, f.defaultInformer)
}

func (f *typ0crdInformer) Lister() v1.Typ0crdLister {
	return v1.NewTyp0crdLister(f.Informer().GetIndexer())
}
