apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: typ4crds.crd.devcluster.network.com
spec:
  group: crd.devcluster.network.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                typ4crdSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer

  scope: Namespaced
  names:
    # plural name to be used in the url
    # /apis/crd.devcluster.network.com/v1/typ4crds
    plural: typ4crds
    shortNames: 
    - t4
    singular: typ4crd
    kind: Typ4crd


              