apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: typ0crds.crd.devcluster.com
spec:
  group: crd.devcluster.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                typ0crdSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                url:
                  type: string

  scope: Namespaced
  
  names:
    # plural name to be used in the url
    # /apis/crd.devcluster.network.com/v1/typ0crds
    plural: typ0crds
    shortNames: 
    - t0
    singular: typ0crd
    kind: Typ0crd


              