apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: typ2crds.crd.devcluster.network.com
spec:
  group: crd.devcluster.network.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                typ2crdSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer

  scope: Namespaced
  names:
    # plural name to be used in the url
    # /apis/crd.devcluster.network.com/v1/typ2crds
    plural: typ2crds
    shortNames: 
    - t2
    singular: typ2crd
    kind: Typ2crd



              